name: Pruebas Unitarias

on:
  push:
    branches:
      - examen-parcial-1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar dependencias y ejecutar pruebas
      run: |
        npm install
        npm test

    - name: Subir capturas de pantalla
      uses: actions/upload-artifact@v2
      with:
        name: Screenshots
        path: screenshots/

